### PR TITLE
Reworking the hanging indent continuations

### PR DESCRIPTION
**Pull request by kbrose**
After parsing was done, an extra case needed to be considered when dealing
with continuing lines in a hanging indent after closing a nested bracket
pair. See issue #15.

### CODE REVIEW

**Comment by kbrose** [comment]
@DSpeckhals question on how the CI works:

This PR changed the content of `spec/python-indent-spec.coffee`, will the CI run on the version that is currently in the master branch, the version that is in this new PR, or on both?

**Comment by DSpeckhals** [comment]
> will the CI run on the version that is currently in the master branch, the version that is in this new PR, or on both?

It will run on the version in your commit.

**Comment by DSpeckhals** [comment]
@kbrose You can run the tests within Atom fairly easily. Just press `ctrl-alt-p` (at least on Windows and Linux). Here's some more [info](https://atom.io/docs/v1.5.3/hacking-atom-writing-specs#running-specs).

**Comment by kbrose** [comment]
Ahah! Thanks, that will certainly make things a lot quicker and less messy!

**Pull request merged**
